apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  type: NodePort
  selector:
    pod: cluster1-dc1-rack3-sts-0
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 9042
      nodePort: 30042
